//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalkZombieManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ZombieResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZombieResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizTalkZombieManagement.Resources.ZombieResource", typeof(ZombieResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode enable.
        /// </summary>
        public static string Debug_Mode {
            get {
                return ResourceManager.GetString("Debug_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now delete zombie orchestration.
        /// </summary>
        public static string Delete_Zombie_Orchestration {
            get {
                return ResourceManager.GetString("Delete_Zombie_Orchestration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder address is missing.
        /// </summary>
        public static string Error_AddressMissing {
            get {
                return ResourceManager.GetString("Error_AddressMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder for dump {0} is not found.
        /// </summary>
        public static string Error_Folder {
            get {
                return ResourceManager.GetString("Error_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error please, reconfigure Zombie Management, no dump layer found.
        /// </summary>
        public static string Error_NoLayerActivated {
            get {
                return ResourceManager.GetString("Error_NoLayerActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource key desired {0} is not found.
        /// </summary>
        public static string Error_ResourceKeyNotFound {
            get {
                return ResourceManager.GetString("Error_ResourceKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service encounters a problem and need to be stopped.
        /// </summary>
        public static string Error_Stop {
            get {
                return ResourceManager.GetString("Error_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service won&apos;t start due to validation error.
        /// </summary>
        public static string Error_Validation {
            get {
                return ResourceManager.GetString("Error_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event arrived.
        /// </summary>
        public static string EventArrived {
            get {
                return ResourceManager.GetString("EventArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Exception {0} haven&apos;t got a boolean value \n Dump file won&apos;t be activated.
        /// </summary>
        public static string File_Activated_Error {
            get {
                return ResourceManager.GetString("File_Activated_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path contain in {0} is not a valid path, service will not start until you correct it, please open configuration file and correct the DumpFolder key value.
        /// </summary>
        public static string File_Invalid_Path {
            get {
                return ResourceManager.GetString("File_Invalid_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Exception {0} haven&apos;t got a boolean value \n Dump MSMQ won&apos;t be activated.
        /// </summary>
        public static string Msmq_Activated_Error {
            get {
                return ResourceManager.GetString("Msmq_Activated_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified MSMQ {0} doest not exist.
        /// </summary>
        public static string Msmq_PathNotFound {
            get {
                return ResourceManager.GetString("Msmq_PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No zombie message found, the instance {0} is not a zombie instance.
        /// </summary>
        public static string No_Zombie_Found {
            get {
                return ResourceManager.GetString("No_Zombie_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Messages are saved !.
        /// </summary>
        public static string SavedMessage {
            get {
                return ResourceManager.GetString("SavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving all messages.....
        /// </summary>
        public static string SavingMessage {
            get {
                return ResourceManager.GetString("SavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Exception {0} haven&apos;t got a boolean value \n Dump WCF won&apos;t be activated.
        /// </summary>
        public static string WCF_Activated_Error {
            get {
                return ResourceManager.GetString("WCF_Activated_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All message are sent to WCF.
        /// </summary>
        public static string WCF_SavedMessage {
            get {
                return ResourceManager.GetString("WCF_SavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Message over WCF.
        /// </summary>
        public static string WCF_SavingMessage {
            get {
                return ResourceManager.GetString("WCF_SavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message Zombie Found for service instance {0}.
        /// </summary>
        public static string Zombie_Found {
            get {
                return ResourceManager.GetString("Zombie_Found", resourceCulture);
            }
        }
    }
}
